### ISSUE TITLE
store person id and dwell time in dataframe

### ISSUE THREAD

**Issue by pk-1196** [mailrocketsystems/AIComputerVision#11]
Hi ,
In dwell_time_calculation.py , i want to store the time elapsed by each person in a frame in a pandas DataFrame ,
like 
id 1 has stayed 15 sec in frame and suppose id_2 has stayed total 10 sec ..then data frame with only 2 rows ,with 4 columns i.e. Person_id, Start_time, end_time, Total time=end_time - start_time .

**Comment by mailrocketsystems** [comment]
This is not an issue, so closing it. Thanks
