### ISSUE TITLE
GPU support for person_tracking.py

### ISSUE THREAD

**Issue by chrisTopp84** [mailrocketsystems/AIComputerVision#3]
Hi,

this ist not an issue but a question.
I wonder if the GPU is used while running the person_tracking.py example?

Some information about the system I'm workung with:

    Jetson Nano
    Image: jetson-nano-4gb-jp441-sd-card-image
    OpenCV 4.1.1
    CUDA Version 10.2
    Ubuntu 18.04 LTS

I've read some posts about this question but I'm not really sure about the current state. Do you have any idea?

Best regards
chris

**Comment by mailrocketsystems** [comment]
@chrisTopp84 Person tracking code by default uses CPU. Line 11-12 defines the use of hardware. You can mention `cv2.dnn.DNN_TARGET_GPU` in order to use GPU hardware (Not sure but you will have to install intel's open vino environment first)

**Comment by chrisTopp84** [comment]
Thanks a lot for your fast reply.
Could you tell me where I have to paste cv2.dnn.DNN_TARGET_GPU within the person_tracking.py example? 
I will give it a try without installing intel's open vino environment first.

Best regards

**Comment by mailrocketsystems** [comment]
I don't think you can do that without open vino environment and I think you might not install openvino on jetson. Jetson has its own way of handling inferencing over GPU.

**Comment by chrisTopp84** [comment]
Ok, thanks for your reply.
