### ISSUE TITLE
problem with the module for human detection

### ISSUE THREAD

**Issue by georgejrmerheb1** [mailrocketsystems/AIComputerVision#6]
![image](https://user-images.githubusercontent.com/86836664/124275695-cbe06900-db3a-11eb-9a0e-d36b80df46ea.png)
in this image, you could see the problem when I first insert the code. It is stating that "no module is named 'cv2', 'numpy', and 'imutils'.
Can you help with clarifying the problem here?

**Comment by leminhloc2008** [comment]
you didn't install the modules
