### ISSUE TITLE
Open CV issue while rerunning person counter

### ISSUE THREAD

**Issue by nupur0294** [mailrocketsystems/AIComputerVision#7]
All  the codes runs fine but while I run person counter i get following error.

cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/dnn.cpp:1077: error: (-213:The function/feature is not implemented) Unknown backend identifier in function 'wrapMat'

which version of cv2 is compatible to the code?

**Comment by Guttappa1238** [comment]
@nupur0294  comment out  line 10 and 11 in `person_counter.py` it will work!!!!
